version: '2'

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - oroscopo-nodes
    depends_on:
      - node1
      - node2

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./app.js:/usr/src/app/app.js
      - ./views:/usr/src/app/views
      - ./routes:/usr/src/app/routes
      - ./helpers:/usr/src/app/helpers
      - ./models:/usr/src/app/models
      - ./middleware:/usr/src/app/middleware
      - ./node_modules:/usr/src/app/node_modules
      - ./config:/usr/src/app/config
      - ./public:/usr/src/app/public
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - oroscopo-nodes
    depends_on:
      - rabbit

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./app.js:/usr/src/app/app.js
      - ./views:/usr/src/app/views
      - ./routes:/usr/src/app/routes
      - ./helpers:/usr/src/app/helpers
      - ./models:/usr/src/app/models
      - ./middleware:/usr/src/app/middleware
      - ./node_modules:/usr/src/app/node_modules
      - ./config:/usr/src/app/config
      - ./public:/usr/src/app/public
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - oroscopo-nodes
    depends_on:
      - rabbit
  

  mongodb:
    build:
      context: .
      dockerfile: ./docker/database.dockerfile
    volumes:
      - ./mongodb:/data/db
    ports:
      - "5984:5984"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - oroscopo-nodes

  rabbit:
    build:
      context: .
      dockerfile: ./docker/rabbit.dockerfile
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/mnesia
      
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
     - oroscopo-nodes

networks:
  oroscopo-nodes:
    driver: bridge
  
