version: '2'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - mongodb:mongodb
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "8080:80"
    networks:
      - app-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - app-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
    networks:
      - app-network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000"
    environment:
      - INSTANCE=node3
    networks:
      - app-network

  mongodb:
    build:
      context: .
      dockerfile: docker/database.dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules

    ports:
      - "5984:5984"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
