name: GitHub Actions
on:
  push:
    branches: [main]
jobs:
  Actions:
    runs-on: ubuntu-latest
    steps:
      
      #1
      - name: Gcheck
        uses: actions/checkout@v3

      #2
      - name: Start 
        run: docker-compose up -d --build

      #3
      - name: Install node 
        uses: actions/setup-node@v3

      #4
      - name: install dependencies
        run: npm install

      #5
      - name: Run Test
        run: npm test

      #6
      - name: Stop
        if: always() 
        run: docker-compose down