name: GitHub Actions
on:
  push:
    branches: [main]
jobs:
  Actions:
    runs-on: ubuntu-latest
    steps:
      
      #1
      - name: Gcheck
        uses: actions/checkout@v2

      #2
      - name: Start 
        run: docker-compose up -d --build

      #3
      - name: Waiting the startup sequence 
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'

      #4
      - name: Stop
        if: always() 
        run: docker-compose down