name: GitHub Actions
on:
  push:
    branches: [main]
jobs:
  Actions:
    runs-on: ubuntu-latest
    steps:
      
      #1
      - name: Gcheck
        uses: actions/checkout@v3

      #2
      - name: Start 
        run: docker-compose up -d --build

      #3
      - name: Waiting the startup sequence 
        run: sleep 30s

      #4
      - name: Install node & mocha
        uses: actions/setup-node@v3
        run: npm install -g mocha

      #5
      - name: Run Test
        run: npm test --prefix ./src

      #6
      - name: Stop
        if: always() 
        run: docker-compose down